import type { CSSProperties } from "react";

/** Co-located styles for BlastTab (full Tree/Graph blast-radius view). */
export const s = {
  toggleGroup: {
    display: "flex",
    gap: 6,
  } satisfies CSSProperties,
  degradedBadge: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    fontSize: 12.5,
    color: "var(--warn)",
    background: "var(--warn-bg, var(--bg-hover))",
    borderRadius: 6,
    padding: "6px 10px",
    marginBottom: 14,
  } satisfies CSSProperties,
  empty: {
    fontSize: 13,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  summaryText: {
    margin: "0 0 16px",
    fontSize: 14,
    color: "var(--text-secondary)",
    lineHeight: 1.55,
  } satisfies CSSProperties,
  error: {
    fontSize: 13,
    color: "var(--danger)",
    marginBottom: 12,
  } satisfies CSSProperties,
  symbolList: {
    display: "flex",
    flexDirection: "column",
    gap: 20,
  } satisfies CSSProperties,
  symbolBlock: {
    border: "1px solid var(--border)",
    borderRadius: 8,
    background: "var(--bg-elevated)",
    padding: 16,
    display: "flex",
    flexDirection: "column",
    gap: 8,
  } satisfies CSSProperties,
  symbolTitleRow: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    width: "100%",
    background: "none",
    border: "none",
    padding: 0,
    cursor: "pointer",
    textAlign: "left",
    marginBottom: 4,
  } satisfies CSSProperties,
  symbolName: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    fontSize: 15,
    fontWeight: 700,
    color: "var(--text-primary)",
  } satisfies CSSProperties,
  symbolIcon: {
    color: "var(--text-muted)",
    flexShrink: 0,
  } satisfies CSSProperties,
  symbolCountTag: {
    fontSize: 12,
    fontWeight: 500,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  chevron: (open: boolean): CSSProperties => ({
    color: "var(--text-muted)",
    transform: open ? "rotate(0deg)" : "rotate(-90deg)",
    transition: "transform 120ms ease",
    flexShrink: 0,
  }),
  sectionLabel: {
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: "0.06em",
    textTransform: "uppercase",
    color: "var(--text-muted)",
    marginTop: 4,
  } satisfies CSSProperties,
  callerList: {
    margin: 0,
    padding: 0,
    listStyle: "none",
    display: "flex",
    flexDirection: "column",
    gap: 4,
  } satisfies CSSProperties,
  callerLine: {
    display: "flex",
    alignItems: "center",
    gap: 6,
  } satisfies CSSProperties,
  callerIcon: {
    color: "var(--text-muted)",
    flexShrink: 0,
  } satisfies CSSProperties,
  chipRow: {
    display: "flex",
    flexWrap: "wrap",
    gap: 6,
  } satisfies CSSProperties,
  graphWrap: {
    border: "1px solid var(--border)",
    borderRadius: 8,
    background: "var(--bg-elevated)",
    padding: 16,
    overflowX: "auto",
  } satisfies CSSProperties,
  statsLine: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    fontSize: 12,
    color: "var(--text-muted)",
    marginBottom: 14,
  } satisfies CSSProperties,
  priorSection: {
    borderTop: "1px solid var(--border)",
    paddingTop: 12,
    marginTop: 20,
  } satisfies CSSProperties,
  priorHeader: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    width: "100%",
    background: "none",
    border: "none",
    padding: "2px 0",
    cursor: "pointer",
    textAlign: "left",
    fontSize: 13.5,
    fontWeight: 600,
    color: "var(--text-primary)",
  } satisfies CSSProperties,
  priorList: {
    margin: 0,
    padding: "8px 0 2px 22px",
    listStyle: "none",
    display: "flex",
    flexDirection: "column",
    gap: 4,
  } satisfies CSSProperties,
  priorLink: {
    fontSize: 13.5,
    color: "var(--accent-text)",
    textDecoration: "none",
  } satisfies CSSProperties,
} as const;
