import type { CSSProperties } from "react";

export const s = {
  body: { padding: 24, display: "flex", flexDirection: "column", gap: 20 } satisfies CSSProperties,
  stepsBar: { paddingBottom: 4 } satisfies CSSProperties,
  footer: { display: "flex", alignItems: "center", justifyContent: "space-between", gap: 10 } satisfies CSSProperties,
  footerRight: { display: "flex", alignItems: "center", gap: 10, marginLeft: "auto" } satisfies CSSProperties,

  // TargetStep
  targetGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(2, 1fr)",
    gap: 12,
  } satisfies CSSProperties,
  targetCard: (active: boolean, disabled: boolean): CSSProperties => ({
    display: "flex",
    flexDirection: "column",
    gap: 8,
    padding: 14,
    borderRadius: 10,
    border: `1.5px solid ${active ? "var(--accent)" : "var(--border-strong)"}`,
    background: active ? "var(--accent-bg, var(--bg-elevated))" : "var(--bg-elevated)",
    cursor: disabled ? "default" : "pointer",
    opacity: disabled && !active ? 0.75 : 1,
    textAlign: "left",
  }),
  targetCardTop: { display: "flex", alignItems: "center", gap: 8 } satisfies CSSProperties,
  targetCardTitle: { fontSize: 14, fontWeight: 700, flex: 1 } satisfies CSSProperties,
  targetCardDesc: { fontSize: 12.5, color: "var(--text-secondary)" } satisfies CSSProperties,
  notAvailable: { fontSize: 12, color: "var(--warn, var(--text-muted))", fontWeight: 600 } satisfies CSSProperties,

  warningBox: {
    display: "flex",
    flexDirection: "column",
    gap: 10,
    padding: 12,
    borderRadius: 8,
    border: "1px solid var(--warn, var(--border-strong))",
    background: "var(--warn-bg, var(--bg-elevated))",
  } satisfies CSSProperties,
  warningHead: { display: "flex", alignItems: "flex-start", gap: 8, fontSize: 13 } satisfies CSSProperties,

  // PreviewStep
  previewGrid: {
    display: "grid",
    gridTemplateColumns: "220px 1fr",
    gap: 16,
    minHeight: 320,
  } satisfies CSSProperties,
  fileList: { display: "flex", flexDirection: "column", gap: 4 } satisfies CSSProperties,
  fileRow: (active: boolean): CSSProperties => ({
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "8px 10px",
    borderRadius: 6,
    border: "1px solid " + (active ? "var(--accent)" : "transparent"),
    background: active ? "var(--bg-hover)" : "transparent",
    cursor: "pointer",
    textAlign: "left",
    width: "100%",
    fontSize: 12.5,
  }),
  filePath: { flex: 1, minWidth: 0, overflowWrap: "anywhere" } satisfies CSSProperties,
  codePane: {
    borderRadius: 8,
    border: "1px solid var(--border)",
    background: "var(--bg-surface)",
    padding: 12,
    overflow: "auto",
    display: "flex",
    flexDirection: "column",
    gap: 8,
  } satisfies CSSProperties,
  codeBlock: {
    margin: 0,
    fontSize: 12.5,
    lineHeight: 1.5,
    whiteSpace: "pre-wrap",
    overflowWrap: "anywhere",
  } satisfies CSSProperties,
  placeholder: { fontSize: 13, color: "var(--text-muted)", padding: "20px 4px" } satisfies CSSProperties,

  // ConfigureStep
  checkboxList: { display: "flex", flexDirection: "column", gap: 10 } satisfies CSSProperties,
  radioList: { display: "flex", flexDirection: "column", gap: 8 } satisfies CSSProperties,
  table: { width: "100%", borderCollapse: "collapse", fontSize: 13 } satisfies CSSProperties,
  tableHeadCell: {
    textAlign: "left",
    padding: "6px 10px",
    fontSize: 11,
    textTransform: "uppercase",
    letterSpacing: "0.05em",
    color: "var(--text-muted)",
    borderBottom: "1px solid var(--border)",
  } satisfies CSSProperties,
  tableCell: { padding: "8px 10px", borderBottom: "1px solid var(--border)", verticalAlign: "top" } satisfies CSSProperties,
  calloutBox: {
    display: "flex",
    flexDirection: "column",
    gap: 6,
    padding: 12,
    borderRadius: 8,
    border: "1px solid var(--border-strong)",
    background: "var(--bg-elevated)",
  } satisfies CSSProperties,
  calloutTitle: { display: "flex", alignItems: "center", gap: 8, fontSize: 13, fontWeight: 700 } satisfies CSSProperties,
  calloutBody: { fontSize: 12.5, color: "var(--text-secondary)", lineHeight: 1.5 } satisfies CSSProperties,

  // InstallStep
  installCard: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
    padding: 16,
    borderRadius: 10,
    border: "1px solid var(--border-strong)",
    background: "var(--bg-elevated)",
  } satisfies CSSProperties,
  installCardTop: { display: "flex", alignItems: "center", gap: 8 } satisfies CSSProperties,
  installCardTitle: { fontSize: 14, fontWeight: 700, flex: 1 } satisfies CSSProperties,
  installCardBody: { fontSize: 12.5, color: "var(--text-secondary)", lineHeight: 1.5 } satisfies CSSProperties,
  successBox: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: 12,
    borderRadius: 8,
    border: "1px solid var(--ok)",
    background: "var(--ok-bg, var(--bg-elevated))",
    fontSize: 13,
  } satisfies CSSProperties,
};
